name: Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Configurar pnpm PRIMERO
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      # 2. Configurar Node.js después
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'  # Habilita caching para pnpm

      - name: Install Rust targets
        run: |
          rustup target add x86_64-pc-windows-msvc
          rustup target add x86_64-unknown-linux-gnu
          sudo apt-get update
          sudo apt-get install -y mingw-w64  # Necesario para compilar Windows en Linux
      
          # 3. Instalar dependencias
      - name: Install dependencies
        run: pnpm install

      - name: Build Windows
        run: pnpm tauri build --target x86_64-pc-windows-msvc
        env:
          TAURI_UPDATER_PRIVATE_KEY: ${{ secrets.TAURI_UPDATER_PRIVATE_KEY }}
          TAURI_UPDATER_KEY_PASSWORD: ${{ secrets.TAURI_UPDATER_KEY_PASSWORD }}

      - name: Build Linux
        run: pnpm tauri build --target x86_64-unknown-linux-gnu
        env:
          TAURI_UPDATER_PRIVATE_KEY: ${{ secrets.TAURI_UPDATER_PRIVATE_KEY }}
          TAURI_UPDATER_KEY_PASSWORD: ${{ secrets.TAURI_UPDATER_KEY_PASSWORD }}

      - name: Generate latest.json
        run: |
          VERSION=$(echo ${{ github.ref_name }} | sed 's/v//')
          PUB_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          
          # Firmar Windows
          SIGNATURE_WIN=$(pnpm tauri plugin updater sign -w ${{ secrets.TAURI_UPDATER_PRIVATE_KEY }} -P ${{ secrets.TAURI_UPDATER_KEY_PASSWORD }} ./src-tauri/target/x86_64-pc-windows-msvc/release/bundle/msi/APPNAME_${VERSION}_x64.msi)

          # Firmar Linux
          SIGNATURE_LINUX=$(pnpm tauri plugin updater sign -w ${{ secrets.TAURI_UPDATER_PRIVATE_KEY }} -P ${{ secrets.TAURI_UPDATER_KEY_PASSWORD }} ./src-tauri/target/x86_64-unknown-linux-gnu/release/bundle/deb/APPNAME_${VERSION}_amd64.deb)

          echo '{
            "version": "'$VERSION'",
            "notes": "Actualización Windows + Linux",
            "pub_date": "'$PUB_DATE'",
            "platforms": {
              "windows-x86_64": {
                "signature": "'$SIGNATURE_WIN'",
                "url": "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/APPNAME_${VERSION}_x64.msi"
              },
              "linux-x86_64": {
                "signature": "'$SIGNATURE_LINUX'",
                "url": "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/APPNAME_${VERSION}_amd64.deb"
              }
            }
          }' > latest.json

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            src-tauri/target/x86_64-pc-windows-msvc/release/bundle/msi/*.msi
            src-tauri/target/x86_64-unknown-linux-gnu/release/bundle/deb/*.deb
            latest.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}